(custom-set-variables
 '(auto-fill-mode t)
 '(blink-cursor-mode nil)
 '(tool-bar-mode nil)
 '(scroll-bar-mode nil)
 '(dynamic-completion-mode t)
 '(delete-selection-mode t)
 '(fido-vertical-mode t)
 '(electric-pair-mode t)
 '(ring-bell-function 'ignore)
 '(insert-directory-program "gls")
 '(indent-tabs-mode nil)
 '(pixel-scroll-precision-mode t)
 '(recentf-mode t)
 '(repeat-mode t)
 '(savehist-mode t)
 '(dired-listing-switches "-aGFhlv --dired --group-directories-first --time-style=long-iso")
 '(text-scale-mode-step 1.1)
 '(winner-mode t)
 '(modus-themes-to-toggle '(modus-operandi-tinted modus-vivendi))
 '(modus-themes-bold-constructs t)
 '(modus-themes-italic-constructs t)
 '(modus-themes-variable-pitch-ui nil)
 '(completion-styles '(basic flex))
 '(completion-auto-help 'visible)
 '(completion-auto-select t)
 '(completions-max-height 15)
 '(completions-format 'one-column)
 '(completions-sort 'alphabetical)
 '(completion-ignore-case t)
 '(global-completion-preview-mode t)
 '(completion-preview-minimum-symbol-length 2)
 '(epg-pinentry-mode 'loopback))

(keymap-set completion-preview-active-mode-map "M-n" #'completion-preview-next-candidate)
(keymap-set completion-preview-active-mode-map "M-p" #'completion-preview-prev-candidate)

(global-set-key (kbd "M-j") 'join-line)

(when (display-graphic-p)
  (global-unset-key (kbd "C-z"))
  (global-unset-key (kbd "C-<wheel-up>"))
  (global-unset-key (kbd "C-<wheel-down>")))

(load-theme 'modus-operandi-tinted)
(define-key global-map (kbd "<f5>") #'modus-themes-toggle)

(setq make-backup-files nil)
